### ISSUE TITLE
Dataset /mnt/ssd/pythia/*.jsonl.zst

### ISSUE THREAD

**Issue by 32r81b** [theblackcat102/unify-learning-paradigms#1]
Hi. I'm new in ul2 and want to train my own t5 model. I'm tying to implement mixture of denoisers from your code. But in you code you use some custom dataset from "/mnt/ssd/pythia/*.jsonl.zst". How I can get it dataset?

**Comment by 32r81b** [comment]
If I use my custom dataset I faces with error:

```
There seems to be not a single sample in your epoch_iterator, stopping training at step 0! This is expected if you're using an IterableDataset and set num_steps (100) higher than the number of available samples.



self.state.global_step: 0
Traceback (most recent call last):
  File "/workspaces/t5_kz/train_t5.py", line 81, in <module>
    trainer.train()
  File "/transformers/src/transformers/trainer.py", line 1696, in train
    return inner_training_loop(
  File "/transformers/src/transformers/trainer.py", line 2101, in _inner_training_loop
    train_loss = self._total_loss_scalar / self.state.global_step
ZeroDivisionError: float division by zero
```

**Comment by 32r81b** [comment]
I think the problem was with code in [test_dataset.py](https://github.com/theblackcat102/unify-learning-paradigms/tree/master/tests/test_dataset.py)

All __iters__ end up with code where you yeld result only if length of tokens more than max_length.
I change thise:
```
                                if len(tokens) >= self.max_length:
                                    yield { 'input_ids': tokens[:self.max_length] }
```


To:

```
                                if len(tokens) >= self.max_length:
                                    yield { 'input_ids': tokens[:self.max_length] }
                                else:
                                    yield { 'input_ids': tokens }
```

And error "float division by zero" disapear.
